method: grid
metric:
  goal: minimize
  name: loss
parameters:
  batch_size:
    values:
    - 32
    - 64
    - 128
    - 256
    - 512
    - 1024
    - 2048
    - 4096
  learning_rate:
    values:
    - 0.01
    - 0.2575
    - 0.505
    - 0.7525
    - 1.0
  n_epochs:
    value: 1000
  nodes_per_layer:
    values:
    - - 18
      - 13
      - 8
      - 4
    - - 18
      - 14
      - 11
      - 7
      - 4
    - - 18
      - 15
      - 12
      - 9
      - 6
      - 4
  num_linear_output_layers:
    values:
    - 2
    - 3
